Compile the `tendermint` and `light-client` crates to WASM (#553)
* Enable compiling the tendermint crate to WASM

* Enable compiling the light-client crate to WASM

* Add CI job to build tendermint and light-client crates for WASM

* Formatting

* Install WASM target in CI job

* Fix wrong feature name in rpc crate

* Enable client as default option of rpc crate

* Remove unused import

* Formatting

* Disable default features of rpc crate in light-client

* Disable acceptance test for the light node to work around doc test error

It is currently unclear why this error has appeared, though I suspect it
is a bug in Cargo related to the combination of doc tests and features
flags.

       Doc-tests tendermint-light-client
    error[E0460]: found possibly newer version of crate `tendermint` which `tendermint_rpc` depends on
     --> /Users/coromac/Informal/Code/Current/tendermint-rs/light-client/src/components/io.rs:7:5
      |
    7 | use tendermint_rpc as rpc;
      |     ^^^^^^^^^^^^^^
      |
      = note: perhaps that crate needs to be recompiled?
      = note: the following crate versions were found:
              crate `tendermint`: /Users/coromac/Informal/Code/Current/tendermint-rs/target/debug/deps/libtendermint.rlib
              crate `tendermint`: /Users/coromac/Informal/Code/Current/tendermint-rs/target/debug/deps/libtendermint-735716e8d731096d.rmeta
              crate `tendermint_rpc`: /Users/coromac/Informal/Code/Current/tendermint-rs/target/debug/deps/libtendermint_rpc-ad41c355acf2752f.rlib

    error: aborting due to previous error

* Update changelog

* Add PR number to the changelog entry

* Update changelog

* Add link to related issue to ignored test

* Formatting